"""empty message

Revision ID: 11877b0d5344
Revises: 9c90d2a7a21e
Create Date: 2025-01-20 16:30:46.943738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11877b0d5344'
down_revision = '9c90d2a7a21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
